-- Tabla de cuentas
CREATE TABLE IF NOT EXISTS `accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `premdays` int(11) NOT NULL DEFAULT 0,
  `lastday` int(10) unsigned NOT NULL DEFAULT 0,
  `key` varchar(20) NOT NULL DEFAULT '0',
  `blocked` tinyint(1) NOT NULL DEFAULT 0,
  `warnings` int(11) NOT NULL DEFAULT 0,
  `group_id` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Tabla de jugadores (ajusta según tu schema de TFS)
CREATE TABLE IF NOT EXISTS `players` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `account_id` int(11) NOT NULL,
  `group_id` int(11) NOT NULL DEFAULT 1,
  `level` int(11) NOT NULL DEFAULT 8,
  `vocation` int(11) NOT NULL DEFAULT 0,
  `health` int(11) NOT NULL DEFAULT 185,
  `healthmax` int(11) NOT NULL DEFAULT 185,
  `experience` bigint(20) NOT NULL DEFAULT 4200,
  `lookbody` int(11) NOT NULL DEFAULT 68,
  `lookfeet` int(11) NOT NULL DEFAULT 76,
  `lookhead` int(11) NOT NULL DEFAULT 78,
  `looklegs` int(11) NOT NULL DEFAULT 58,
  `looktype` int(11) NOT NULL DEFAULT 136,
  `maglevel` int(11) NOT NULL DEFAULT 0,
  `mana` int(11) NOT NULL DEFAULT 90,
  `manamax` int(11) NOT NULL DEFAULT 90,
  `soul` int(11) NOT NULL DEFAULT 100,
  `town_id` int(11) NOT NULL DEFAULT 1,
  `posx` int(11) NOT NULL DEFAULT 95,
  `posy` int(11) NOT NULL DEFAULT 117,
  `posz` int(11) NOT NULL DEFAULT 7,
  `cap` int(11) NOT NULL DEFAULT 470,
  `sex` int(11) NOT NULL DEFAULT 1,
  `lastlogin` bigint(20) unsigned NOT NULL DEFAULT 0,
  `lastip` int(10) unsigned NOT NULL DEFAULT 0,
  `save` tinyint(1) NOT NULL DEFAULT 1,
  `conditions` blob NOT NULL,
  `skull` tinyint(1) NOT NULL DEFAULT 0,
  `skulltime` int(11) NOT NULL DEFAULT 0,
  `lastlogout` bigint(20) unsigned NOT NULL DEFAULT 0,
  `blessings` tinyint(2) NOT NULL DEFAULT 1,
  `onlinetime` int(11) NOT NULL DEFAULT 0,
  `deletion` bigint(15) NOT NULL DEFAULT 0,
  `balance` bigint(20) unsigned NOT NULL DEFAULT 0,
  `offlinetraining_time` smalli